### ISSUE TITLE
Package Links error on Sync

### ISSUE THREAD

**Issue by giggsey** [repman-io/repman#446]
Just updated work's instance, and updating GitLab packages gives a result of:

```
Error: Typed property Buddy\Repman\Entity\Organization\Package::$links must not be accessed before initialization
Logs:
Reading composer.json of org/package (1.1.2)
...
```

I can't reproduce this locally or on repman.io. We're using the docker-compose setup.

**Comment by akondas** [comment]
This looks like a cache problem to me. How do you make update?

**Comment by giggsey** [comment]
> git pull
> docker-compose up -d

It pulled the correct image

**Comment by akondas** [comment]
It seems that the cached volume is not cleared with this configuration. You can quickly remove the volume "/ap /var/cache", this should fix the error. In the long run, we have to check it out, apparently docker has changed something again in the latest version.

More details: https://github.com/repman-io/repman/pull/420

**Comment by giggsey** [comment]
Just noticed that, and wiped var/cache and restarted all the containers.

The cache directory is now empty, and it still errors.

**Comment by karniv00l** [comment]
@giggsey did you make any modifications to the compose file? `docker-compose.override.yml` maybe? Cache directory is overridden so it's not shared with the host or any other containers and it's created from scratch every time container starts.

**Comment by giggsey** [comment]
@karniv00l Found the actual cache directory hidden within docker, and it had files from March in it. Wiped that directory & restarted, still no luck. Files have populated with today's date though.

git diff shows the only modification to docker-compose is changing the nginx port. No override file present either.

**Comment by karniv00l** [comment]
Make sure that all containers have been restarted, otherwise cache volume might not be recreated:

```
docker-compose down && docker-compose up -d
```

**Comment by giggsey** [comment]
That did it. I was only stopping + starting.

Thanks!

**Comment by akondas** [comment]
Ok, for the sake of clarity why this is so:
1. `docker-compose up -d`
 

> If there are existing containers for a service, and the service’s configuration or image was changed after the container’s creation, docker-compose up picks up the changes by stopping and recreating the containers (**preserving mounted volumes**)

2. `docker-compose down`

> Anonymous volumes are not removed by default. However, as they don’t have a stable name, they will not be automatically mounted by a subsequent up. For data that needs to persist between updates, use host or named volumes.

On our side, `var/cache` is just an anonymous volume, which is why running only `docker-compose up -d` allowed the cache data to survive.
